ARG BASE_IMAGE_TAG=develop-embedding_api_20240327-2404061715

# 自己的dockerfile制作的镜像
FROM mirrors.tencent.com/zyp-fibona-ai/fibona-mas-base:${BASE_IMAGE_TAG}

# 设置工作目录
WORKDIR /app

# 复制应用程序代码到容器中
COPY . /app
